#!/usr/bin/env python3
"""
stamp_nav.py — writes the shared site header (top bar + two-level menu) and the
footer "Quick Links" list into every page, so the menu is edited in ONE place
(the NAV list below) and copied into each page's static HTML (keeps links crawlable).

Usage:  python3 tools/stamp_nav.py        (run from the website folder)
Pages are found by name; the header sits between  <!-- NAV:START -->  and  <!-- NAV:END -->.
"""
import re, sys, os, html

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..')) if os.path.basename(os.path.dirname(os.path.abspath(__file__))) == 'tools' else os.getcwd()
if len(sys.argv) > 1: ROOT = os.path.abspath(sys.argv[1])

# ── THE MENU ── (label, link, [children])  ──────────────────────────────
NAV = [
  ("Home",            "HOME",                          []),
  ("About",           "about-church.html",             [("Our Church", "about-church.html"),
                                                        ("Syro Malabar Church", "about-syro-malabar-church.html")]),
  ("Faith Formation", "faith-formation.html",          [("Religious Education", "religious-education.html"),
                                                        ("CML (Cherupushpam Mission League)", "cml.html"),
                                                        ("Youth Faith Formation", "youth-faith-formation.html")]),
  ("Prayer Books",    "prayer-books.html",             []),
  ("Parish Calendar", "calendar.html",                 []),
  ("Media",           "media.html",                    []),
  ("Contact",         "CONTACT",                       []),
]
FOOTER_LINKS = [("About Our Church","about-church.html"),("Faith Formation","faith-formation.html"),
                ("Prayer Books","prayer-books.html"),("Parish Calendar","calendar.html"),
                ("Videos &amp; Photos","media.html"),("Donate","DONATE")]

def resolve(link, is_home):
    if link == "HOME":    return "#home" if is_home else "index.html"
    if link == "CONTACT": return "#contact" if is_home else "index.html#contact"
    if link == "DONATE":  return "#donate" if is_home else "index.html#donate"
    return link

CHEV = '<svg viewBox="0 0 10 6" width="10" height="6" aria-hidden="true" focusable="false"><path d="M1 1l4 4 4-4" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>'

def nav_html(page):
    is_home = page == 'index.html'
    out = []
    for label, link, kids in NAV:
        href = resolve(link, is_home)
        pages = [link] + [k[1] for k in kids]
        cur_self = (link == 'HOME' and is_home) or link == page
        in_group = page in pages
        cls = 'nav-item' + (' has-sub' if kids else '') + (' is-current' if in_group or cur_self else '')
        a_cur = ' aria-current="page"' if cur_self else ''
        li = [f'        <li class="{cls}">',
              f'          <a class="nav-link" href="{href}"{a_cur}>{label}</a>']
        if kids:
            li.append(f'          <button type="button" class="nav-sub-toggle" aria-expanded="false" aria-label="Show {label} pages">{CHEV}</button>')
            li.append('          <ul class="nav-sub">')
            for kl, kh in kids:
                kc = ' aria-current="page"' if kh == page else ''
                li.append(f'            <li><a href="{kh}"{kc}>{html.escape(kl, quote=False)}</a></li>')
            li.append('          </ul>')
        li.append('        </li>')
        out.append('\n'.join(li))
    return '\n'.join(out)

def header_html(page, social):
    is_home = page == 'index.html'
    donate = resolve('DONATE', is_home)
    brand = resolve('HOME', is_home)
    return f'''<!-- NAV:START — generated by tools/stamp_nav.py (edit the NAV list there, then re-run) -->
  <div class="topbar" role="complementary" aria-label="Social media and donate">
    <div class="topbar-inner">
{social}
      <div class="topbar-right">
        <a href="{donate}" class="topbar-donate-btn">Donate</a>
      </div>
    </div>
  </div>

  <header class="sticky-bar visible" id="stickyBar">
    <div class="sticky-bar-inner">
      <a href="{brand}" class="sticky-brand" aria-label="Our Lady Of Assumption — Home">
        <img src="images/churchlogo.png" alt="Parish Logo" class="sticky-logo" width="38" height="38" onerror="this.style.display='none'">
        <div class="sticky-name-group">
          <span class="sticky-name">Our Lady Of Assumption</span>
          <span class="sticky-name-sub">Syro Malabar Catholic Mission</span>
        </div>
      </a>
      <button type="button" class="nav-toggle" id="navToggle" aria-label="Open menu" aria-expanded="false" aria-controls="mainNav"><span></span><span></span><span></span></button>
      <nav class="main-nav" id="mainNav" aria-label="Main">
      <ul class="nav-list">
{nav_html(page)}
      </ul>
      </nav>
    </div>
  </header>
  <!-- NAV:END -->
'''

def footer_links(page):
    is_home = page == 'index.html'
    lis = '\n'.join(f'            <li><a href="{resolve(h,is_home)}">{l}</a></li>' for l, h in FOOTER_LINKS)
    return f'<h4>Quick Links</h4>\n          <ul role="list">\n{lis}\n          </ul>'

def stamp(page, src):
    pat = r'(      <div class="topbar-social".*?</div>)\n      <div class="topbar-right">'
    m = re.search(pat, src, re.S) or re.search(pat, open(os.path.join(ROOT, 'index.html'), encoding='utf-8').read(), re.S)
    social = m.group(1)
    hdr = header_html(page, social)
    if '<!-- NAV:START' in src:
        src = re.sub(r'<!-- NAV:START.*?<!-- NAV:END -->\n', lambda m: hdr, src, flags=re.S)
    else:
        src = re.sub(r'(<a href="#main-content" class="skip-link">[^<]*</a>\n).*?(?=\n\s*<main)',
                     lambda m: m.group(1) + '\n  ' + hdr, src, count=1, flags=re.S)
    src = re.sub(r'<h4>Quick Links</h4>\s*<ul role="list">.*?</ul>', lambda m: footer_links(page), src, flags=re.S)
    return src

if __name__ == '__main__':
    pages = sorted(f for f in os.listdir(ROOT) if f.endswith('.html') and f not in ('index - Copy.html',))
    for p in pages:
        path = os.path.join(ROOT, p)
        s = open(path, encoding='utf-8').read()
        if 'skip-link' not in s: continue   # e.g. redirect stubs
        n = stamp(p, s)
        if n != s:
            open(path, 'w', encoding='utf-8', newline='').write(n); print('stamped', p)
        else: print('unchanged', p)
